<div class="text"><img src="img/joseilton.jpg" alt="" align="left"   hspace="10px"/><p>&nbsp;&nbsp;J&aacute; estamos realizando estudos e o sistema ira migrar 100% para o modelo MVC e ter&aacute; como base o Zend Framework, simplificando, isto lhe dar&aacute; independ&ecirc;ncia quanto ao desenvolvedor, continuidade, adapta&ccedil;&atilde;o as suas necessidades, n&atilde;o havendo necessidade de entrar em contato conosco para implanta&ccedil;&atilde;o ou personaliza&ccedil;&atilde;o que voc&ecirc; achar conveniente. Para tanto quem vier a implantar as altera&ccedil;&otilde;es, que n&atilde;o n&oacute;s, dever&aacute; obrigatoriamente ter conhecimento deste padr&otilde;es.</p>
	<p> &nbsp;&nbsp;A total falta de um sistema personalizado, moderno, isento de pretens&otilde;es exclusivamente financeiras, e pensado para facilitar e automatizar os trabalhos corriqueiros da secret&aacute;ria da igreja e auxiliar a dire&ccedil;&atilde;o nas tomadas de decis&otilde;es.</p>
	<p>&nbsp;&nbsp;Atualmente os m&oacute;dulos est&atilde;o concentrados no apoio aos servi&ccedil;os desenvolvidos na secret&aacute;ria executiva da igreja e ainda notamos a aus&ecirc;ncia de alguns servi&ccedil;os importantes, tais como: cartas convites, circulares e alguns relat&oacute;rios, os passos, ap&oacute;s a conclus&atilde;o das demais necessidades da secret&aacute;ria executiva, ser&aacute; sua integra&ccedil;&atilde;o a administra&ccedil;&atilde;o patrimonial, escola b&iacute;blica, financeira, agenda entre outros.</p>
	<p> &nbsp;&nbsp;Esperamos que os usu&aacute;rios deste sistema possa enviar sua opini&atilde;o e sugest&otilde;es para que seja analisada e talvez disponibilizado nas novas atualiza&ccedil;&otilde;es.</p>
	<p> &nbsp;&nbsp;O Senhor Jesus esteve presente durante todo desenvolvimento me dando o rumo em meio a tantos c&oacute;digos. Espero no Deus de Abra&atilde;o, Isaque e Jac&oacute; que o uso deste software ajude a aben&ccedil;oar sua igreja, facilitando trabalhos e lhe permitindo mais tempo e dedica&ccedil;&atilde;o nas outras &aacute;reas da obra de Deus.</p>
	<p>&nbsp;&nbsp; Deus aben&ccedil;oe a igreja!</p>
</div>
<h1>Desenvolvedor: Joseilton Costa Bruce</h1>
<h2>Email para contato: hiltonbruce@gmail.com</h2>
<h2>Telefone de contato: 55 83 </h2>
<h2>Brasil - Paraíba - Bayeux</h2>
